import selectArrow from "../selectArrow.png";
export default {
  mainContainer: {
    height: "495px",
    width: "375px",
    position: "absolute",
    top: "0px",
    boxSizing: "border-box",
  },
  blackBackground: {
    height: "35px",
    width: "375px",
    boxSizing: "border-box",
    backgroundColor: "rgba(0,0,0,0.2)",
  },
  whiteBackground: {
    height: "460px",
    width: "375px",
    boxSizing: "border-box",
    backgroundColor: "white",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    position: "relative",
    padding: "16px",
  },
  cancleButton: {
    position: "absolute",
    top: "16px",
    right: "16px",
    cursor: "pointer",
  },
  selectButton: {
    height: "38px",
    width: "100%",
    boxSizing: "border-box",
    border: "1px solid #C4C4C4",
    marginTop: "18px",
    position: "relative",
  },
  input: {
    border: "none",
    width: "80%",
    height: "100%",
    position: "absolute",
    boxSizing: "border-box",
    display: "none",

    ":focus": {
      outline: "none",
      border: "none",
      boxShadow: "none",
    },
    top: "0px",
    left: "10px",
    fontFamily: "Gotham",
    fontSize: "14px",
  },
  selectArrow: {
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center center",
    width: "20px",
    height: "20px",
    position: "absolute",
    top: "50%",
    right: "15px",
    transform: "translateY(-50%)",
    cursor: "pointer",
    backgroundImage: `url(${selectArrow})`,
  },
  selectCategory: {
    position: "absolute",
    textAlign: "center",
    top: "50%",
    left: "12px",
    transform: "translateY(-50%)",
    zIndex: "10",
    fontFamily: "Gotham",
    fontSize: "14px",
    textTransform: "capitalize",
    cursor: "default",
  },
  optionsContainer: {
    position: "absolute",
    width: "calc(100% + 2px)",
    maxHeight: "255px",
    boxSizing: "border-box",
    gap: "10px",
    top: "37px",
    left: "-1px",
    display: "flex",
    flexDirection: "column",
    borderTop: "none",
    borderLeft: "1px solid #C7C7C7",
    borderRight: "1px solid #C7C7C7",
    borderBottom: "1px solid #C7C7C7",
    zIndex: "100",
    backgroundColor: "white",
  },
  category: {
    color: "#C7C7C7",
    fontFamily: "Gotham",
    fontSize: "14px",
    boxSizing: "border-box",
    height: "25px",
    padding: "4px 0px 4px 12px",
    display: "flex",
    alignItems: "center",
    cursor: "default",
  },
  allProductDiv: {
    fontFamily: "Gotham",
    fontSize: "14px",
    boxSizing: "border-box",
    minHeight: "25px",
    padding: "4px 0px 4px 12px",
    display: "flex",
    alignItems: "center",
    color: "black",
    cursor: "pointer",
    marginTop: "10px",
    ":hover": {
      backgroundColor: "#878787",
    },
  },
  productName: {
    fontFamily: "Gotham",
    fontSize: "14px",
    boxSizing: "border-box",
    minHeight: "25px",
    padding: "4px 0px 4px 22px",
    display: "flex",
    alignItems: "center",
    color: "black",
    cursor: "pointer",
    zIndex: "999",
    ":hover": {
      backgroundColor: "#878787",
    },
  },
};
