export default {
  mainContainer: {
    width: "375px",
    overflow: "hidden",
    position: "relative",
  },
  backgroundImage: {
    width: "100%",
    height: "100%",
  },
  backButton: {
    backgroundRepeat: "no-repeat",
    backgroundSize: "contain",
    backgroundPosition: "center center",
    zIndex: "999",
    height: "30px",
    width: "30px",
    position: "absolute",
    top: "10px",
    left: "10px",
    cursor: "pointer",
  },
  cancelButton: {
    backgroundRepeat: "no-repeat",
    backgroundSize: "contain",
    backgroundPosition: "center center",
    zIndex: "999",
    height: "30px",
    width: "30px",
    position: "absolute",
    top: "10px",
    right: "10px",
    cursor: "pointer",
  },
  resetButton: {
    backgroundRepeat: "no-repeat",
    backgroundSize: "contain",
    backgroundPosition: "center center",
    zIndex: "999",
    height: "35px",
    width: "35px",
    position: "absolute",
    bottom: "70px",
    right: "10px",
    cursor: "pointer",
  },
  compareButton: {
    backgroundRepeat: "no-repeat",
    backgroundSize: "contain",
    backgroundPosition: "center center",
    zIndex: "999",
    height: "35px",
    width: "35px",
    position: "absolute",
    bottom: "25px",
    right: "10px",
    cursor: "pointer",
  },
};
